apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
secretGenerator:
   - name:  mysql-pass
     literals:
          - password=redhat
resources:
       - vish-efs-provisioner.yml
       - vish-create-rbac.yml
       - vish-create-storage.yml
       - vish-deploy-mysql.yml
       - vish-create-deploy-wix.yml
