apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: vish-aws-efs2
provisioner: lw-course/aws-efs2

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: vish-efs-wix
  annotations:
    volume.beta.kubernetes.io/storage-class: "vish-aws-efs2"
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: vish-efs-mysql
  annotations:
    volume.beta.kubernetes.io/storage-class: "vish-aws-efs2"
spec:
  accessModes:
    - ReadWriteMany
  resources:
        requests:
             storage: 5Gi